# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MPI Manual
tagline:
url:              hhtps://jianhuanliu.github.io
baseurl:          /mpi_manual
author:
  name:           Jianhuan Liu
  url:            https://github.com/jianhuanliu/
  email:          j.liu-4@tudelft.nl
plugins:
  - jekyll-redirect-from

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jianhuanliu/mpi_manual
  code:           https://github.com/jianhuanliu/mpi_manuan/tree/gh-pages
pages_list:
  Tutorials:    'tutorials'
  About:                'about'
#Recommended Books:    'recommended-books'
